# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityB1E',
            fields=[
                ('unix_ts', models.IntegerField(primary_key=True, serialize=False)),
                ('v', models.FloatField(db_column='V')),
                ('i', models.FloatField(db_column='I')),
                ('f', models.FloatField()),
                ('dpf', models.FloatField(db_column='DPF')),
                ('apf', models.FloatField(db_column='APF')),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
                ('s', models.IntegerField(db_column='S')),
                ('st', models.IntegerField(db_column='St')),
            ],
            options={
                'db_table': 'electricity_b1e',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricityFge',
            fields=[
                ('unix_ts', models.IntegerField(primary_key=True, serialize=False)),
                ('v', models.FloatField(db_column='V')),
                ('i', models.FloatField(db_column='I')),
                ('f', models.FloatField()),
                ('dpf', models.FloatField(db_column='DPF')),
                ('apf', models.FloatField(db_column='APF')),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
                ('s', models.IntegerField(db_column='S')),
                ('st', models.IntegerField(db_column='St')),
            ],
            options={
                'db_table': 'electricity_fge',
                'managed': False,
            },
        ),
    ]
