# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityCwe',
            fields=[
                ('unix_ts', models.IntegerField(primary_key=True, serialize=False)),
                ('v', models.FloatField(db_column='V')),
                ('i', models.FloatField(db_column='I')),
                ('f', models.FloatField()),
                ('dpf', models.FloatField(db_column='DPF')),
                ('apf', models.FloatField(db_column='APF')),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
                ('s', models.IntegerField(db_column='S')),
                ('st', models.IntegerField(db_column='St')),
            ],
            options={
                'db_table': 'electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricityDwe',
            fields=[
                ('unix_ts', models.IntegerField(primary_key=True, serialize=False)),
                ('v', models.FloatField(db_column='V')),
                ('i', models.FloatField(db_column='I')),
                ('f', models.FloatField()),
                ('dpf', models.FloatField(db_column='DPF')),
                ('apf', models.FloatField(db_column='APF')),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
                ('s', models.IntegerField(db_column='S')),
                ('st', models.IntegerField(db_column='St')),
            ],
            options={
                'db_table': 'electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreDayElectricityCwe',
            fields=[
                ('date_day', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_day_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreDayElectricityDwe',
            fields=[
                ('date_day', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_day_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreDayElectricityFge',
            fields=[
                ('date_day', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_day_electricity_fge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreElectricityCwe',
            fields=[
                ('time_ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreElectricityDwe',
            fields=[
                ('time_ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreElectricityFge',
            fields=[
                ('time_ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('p', models.IntegerField(db_column='P')),
                ('pt', models.IntegerField(db_column='Pt')),
                ('q', models.IntegerField(db_column='Q')),
                ('qt', models.IntegerField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_electricity_fge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreHourElectricityCwe',
            fields=[
                ('datetime_hour', models.DateTimeField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_hour_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreHourElectricityDwe',
            fields=[
                ('datetime_hour', models.DateTimeField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_hour_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreHourElectricityFge',
            fields=[
                ('datetime_hour', models.DateTimeField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_hour_electricity_fge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreMonthElectricityCwe',
            fields=[
                ('date_month', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_month_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreMonthElectricityDwe',
            fields=[
                ('date_month', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_month_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreMonthElectricityFge',
            fields=[
                ('date_month', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_month_electricity_fge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreYearElectricityCwe',
            fields=[
                ('date_year', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_year_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreYearElectricityDwe',
            fields=[
                ('date_year', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_year_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreYearElectricityFge',
            fields=[
                ('date_year', models.DateField(primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
            ],
            options={
                'db_table': 'pre_year_electricity_fge',
                'managed': False,
            },
        ),
    ]
