# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_predelectricityfge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterElectricityFge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField(db_column='P')),
                ('q', models.IntegerField(db_column='Q')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
            ],
            options={
                'db_table': 'cluster_electricity_fge',
                'managed': False,
            },
        ),
    ]
