# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_clusterelectricityfge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterElectricityCwe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField(db_column='P')),
                ('q', models.IntegerField(db_column='Q')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
            ],
            options={
                'db_table': 'cluster_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterElectricityDwe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField(db_column='P')),
                ('q', models.IntegerField(db_column='Q')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
            ],
            options={
                'db_table': 'cluster_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreHourElectricityCwe',
            fields=[
                ('datetime_hour', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
            ],
            options={
                'db_table': 'cluster_pre_hour_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreHourElectricityDwe',
            fields=[
                ('datetime_hour', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
            ],
            options={
                'db_table': 'cluster_pre_hour_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreHourElectricityFge',
            fields=[
                ('datetime_hour', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
            ],
            options={
                'db_table': 'cluster_pre_hour_electricity_fge',
                'managed': False,
            },
        ),
    ]
