# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_clusterelectricitycwe_clusterelectricitydwe_clusterprehourelectricitycwe_clusterprehourelectricitydw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPreDayElectricityCwe',
            fields=[
                ('date_day', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
                ('meaningmodel', models.TextField(db_column='MeaningModel')),
            ],
            options={
                'db_table': 'cluster_pre_day_electricity_cwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreDayElectricityDwe',
            fields=[
                ('date_day', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
                ('meaningmodel', models.TextField(db_column='MeaningModel')),
            ],
            options={
                'db_table': 'cluster_pre_day_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreDayElectricityFge',
            fields=[
                ('date_day', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
                ('meaningmodel', models.TextField(db_column='MeaningModel')),
            ],
            options={
                'db_table': 'cluster_pre_day_electricity_fge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreMonthElectricityDwe',
            fields=[
                ('date_month', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
                ('meaningmodel', models.TextField(db_column='MeaningModel')),
            ],
            options={
                'db_table': 'cluster_pre_month_electricity_dwe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterPreMonthElectricityFge',
            fields=[
                ('date_month', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
                ('meaningmodel', models.TextField(db_column='MeaningModel')),
            ],
            options={
                'db_table': 'cluster_pre_month_electricity_fge',
                'managed': False,
            },
        ),
    ]
