# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_clusterpredayelectricitycwe_clusterpredayelectricitydwe_clusterpredayelectricityfge_clusterpremonthe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPreMonthElectricityCwe',
            fields=[
                ('date_month', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p', models.FloatField(db_column='P')),
                ('pt', models.FloatField(db_column='Pt')),
                ('q', models.FloatField(db_column='Q')),
                ('qt', models.FloatField(db_column='Qt')),
                ('label', models.IntegerField(db_column='Label')),
                ('state', models.IntegerField(db_column='State')),
                ('meaning', models.TextField(db_column='Meaning')),
                ('meaningmodel', models.TextField(db_column='MeaningModel')),
            ],
            options={
                'db_table': 'cluster_pre_month_electricity_cwe',
                'managed': False,
            },
        ),
    ]
